AWSTemplateFormatVersion: "2010-09-09"
Description: ALB*1

Parameters:
  ProjectName:
    Description: Project Name
    Type: String
    Default: unnamed
  Environment:
    Description: Environment
    Type: String
    Default: dev
    AllowedValues:
      - prod
      - dev
      - stg
  VPCID:
    Type: AWS::EC2::VPC::Id
  PublicSubnet1:
    Description: "ELB Subnet 1st"
    Type: AWS::EC2::Subnet::Id
  PublicSubnet2:
    Description: "ELB Subnet 2nd"
    Type: AWS::EC2::Subnet::Id

Resources:
  # --------------------------------------------
  # ELB
  # --------------------------------------------
  ELB1:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: "application"
      Name: !Sub ${ProjectName}-${Environment}-elb
      Scheme: "internet-facing"
      SecurityGroups:
        - !Ref SecurityGroup1
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      IpAddressType: "ipv4"
      LoadBalancerAttributes:
        - Key: "deletion_protection.enabled"
          Value: "false"
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-elb

  ELBListener1:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            StatusCode: 404
            MessageBody: Not Found.
            ContentType: text/plain
      LoadBalancerArn: !Ref ELB1
      Port: 80
      Protocol: HTTP

  #  TargetGroup1:
  #    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
  #    Properties:
  #      VpcId: !Ref VPCID
  #      Name: !Sub ${ProjectName}-${Environment}-tg1
  #      Protocol: "HTTP"
  #      HealthCheckPath: "/"
  #      Port: 80
  #      TargetType: "ip"
  #      HealthCheckIntervalSeconds: 10 # Default is 30.
  #      HealthyThresholdCount: 2 # Default is 5.
  #      HealthCheckTimeoutSeconds: 5
  #      UnhealthyThresholdCount: 2
  #      TargetGroupAttributes:
  #        - Key: "stickiness.enabled"
  #          Value: "false"
  #        - Key: deregistration_delay.timeout_seconds
  #          Value: "60" # default is 300.
  #        - Key: "stickiness.type"
  #          Value: "lb_cookie"
  #        - Key: "stickiness.lb_cookie.duration_seconds"
  #          Value: "86400"
  #        - Key: "slow_start.duration_seconds"
  #          Value: "0"
  #        - Key: "load_balancing.algorithm.type"
  #          Value: "round_robin"

  SecurityGroup1:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${ProjectName}-${Environment}-elb-sg
      GroupDescription: ELB Security Group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"
          Description: "Access from Public"
      VpcId: !Ref VPCID
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-elb-sg

Outputs:
  Listener1:
    Description: "Linstener  ARN"
    Value: !GetAtt ELBListener1.ListenerArn
    Export:
      Name: !Sub ${AWS::StackName}-Listener1
